title: "Origin 解体新書"
summary: |+
  Web 技術解体新書
  第一章 Origin 解体新書 v1.1.0

  Same Origin Policy とは Web において非常に重要なセキュリティモデルの 1 つだ

  fetch や XHR でリクエストを送信したときに、 CORS 違反で失敗したり、 Preflight という謎のリクエストが送信されたりして悩んだ経験があるかもしれない。これらは全て、ユーザーを保護するために設けられた Same Origin Policy という制限を、ブラウザが遵守した結果なのだ。

  本書はこの重要な Origin という概念について、そもそもなぜそんなものが必要なのかという背景や、それがユーザを保護するメカニズム、 JSONP はなぜ危険なのか、 Preflight が飛ぶ理由、 Service Worker など新しい API との連携、 Spectre によって発覚した脆弱性と CORP,COOP,COEP, Origin Isolation など、 Origin を取り巻く関連知識を網羅的/体系的に解説する。

  更新履歴等は Chapter 01 [無料公開] に記載
topics: ["origin", "tech", "web"]
published: true
price: 1000
